version: '3.8'

volumes:
  onboard-vol:

networks:
  iplmt:
    driver: bridge

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: apidb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./volumes/mongo:/etc/mongo
    ports:
      - 27017-27019:27017-27019
    networks:
      - iplmt

  api:
    build:
      context: ./dockerfiles/api/
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    volumes:
      - ./services/api/:/usr/app/
    networks:
      - iplmt
      
  mlflow-db:
    image: postgres:13.1
    container_name: mlflow-db
    environment:
      POSTGRES_DB: mlflowdb
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    networks:
      - iplmt

  mlflow-server:
    build:
      context: ./dockerfiles/mlflow/
      dockerfile: Dockerfile
    container_name: mlflow_server
    environment:
      AWS_REGION: eu-west-3
      AWS_DEFAULT_REGION: eu-west-3
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: adminadmin
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    ports:
      - "5000:5000"
    networks:
      - iplmt
    command: mlflow server --host 0.0.0.0 --backend-store-uri postgresql://mlflow:password@mlflow-db:5432/mlflowdb --default-artifact-root s3://mybucket/

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports: 
      - '9020:9000'
      - '9021:9001'
    volumes: 
      - ./volumes/storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
      MINIO_SITE_REGION: eu-west-3
    networks:
      - iplmt
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mc-service:
    image: minio/mc
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 admin adminadmin;
      /usr/bin/mc mb myminio/mybucket;
      /usr/bin/mc policy set public myminio/mybucket;
      "
    networks:
      - iplmt