version: '3.8'

networks:
  cycle-project:
    driver: bridge

services:
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    networks:
      - cycle-project
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    ports:
      - 8081:8081
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: onboard-classifier
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    networks:
      - cycle-project

  service_api_classifier: &app
    tty: true
    cap_add:
     - SYS_PTRACE
    build:
      context: ./service_api_classifier/
      args:
        requirements: requirements/development.txt
    container_name: service_api_classifier
    environment:
      DEBUG: 1
      SETTINGS_FILE: api.dev.yml
      PYTHONUNBUFFERED: 1
      MONGODB_DATABASE: onboard-classifier
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin
      MONGODB_HOSTNAME: mongo
    restart: always
    depends_on:
      - processing
      - mongo
      - mongo-express
    volumes:
      - ./service_api_classifier:/app:delegated
    networks:
      - cycle-project
    ports:
      - 8080:8080
    command: make adev

  processing:
    build:
      context: ./processing/
      args:
        requirements: requirements/development.txt
    container_name: processing
    environment:
      DEBUG: 1
      SETTINGS_FILE: api.dev.yml
      PYTHONUNBUFFERED: 1
      GRPC_PORT: 50051
      GRPC_HOSTNAME: mongo
    restart: always
    volumes:
      - ./processing:/app:delegated
    networks:
      - cycle-project
    ports:
      - 50051:50051
    command: make run

  # test:
  #   <<: *app
  #   container_name: onboard_classifier_test
  #   ports:
  #     - 8082:8082
  #   entrypoint: py.test -v -p no:warnings
  #   command: ''
  #   networks:
  #     - cycle-project